package com.example.demo.model;

public enum RolPolo {
    ADMINISTRADOR,
    DIRECTORA_POLO_SALUD,
    COORDINADORA,
    CONECTORA_LIDER,
    GESTOR_TECNICO_FINANCIERO,
    GESTORA_PROYECTOS,
    GESTORA_OBRAS_CONSTRUCCIONES
}